name: Publish to WB Asset Server

on: push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2

    - name: Publish app
      uses: Azure/cli@v1.0.0
      with:
        azcliversion: latest
        inlineScript: |
          az storage blob delete-batch -s "\$web" --pattern sign-in\* --connection-string "${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}"
          az storage blob upload-batch -s $GITHUB_WORKSPACE/ -d "\$web" --destination-path sign-in --connection-string "${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}"
